Repository EC-CUBE/mail-magazine-plugin, pull requests merged in 2022-08, with the labels that each got.

#126 Deprecated な html タグが使われているので現行のものに置換する
  Resource/template/admin/confirm.twig
  Resource/template/admin/history_preview.twig
  Resource/template/admin/preview.twig
Labels: bugbounty2022:pr:entry

#125 配信画面、配信履歴画面のレイアウトを調整
  Resource/template/admin/confirm.twig
  Resource/template/admin/history_list.twig
  Resource/template/admin/history_result.twig
  Resource/template/admin/index.twig
  Resource/template/admin/template_edit.twig
  Resource/template/admin/template_list.twig
  Resource/template/admin/template_select.twig
Labels: bug, bugbounty2022:pr:entry

#131 必須マークの追加
  Resource/template/admin/template_edit.twig
Labels: bugbounty2022:pr:entry, bugbounty2022:pr:recognition

#132 必須マーク追加
  Resource/template/admin/mailmagazine.twig
Labels: bugbounty2022:pr:entry, bugbounty2022:pr:recognition

#134 レイアウトの崩れに対応
  Resource/template/admin/index.twig
Labels: bugbounty2022:pr:entry, bugbounty2022:pr:recognition

#136 ボタンのレイアウトを配信画面で統一
  Resource/template/admin/index.twig
  Resource/template/admin/template_list.twig
Labels: bugbounty2022:pr:entry, bugbounty2022:pr:recognition

#138 ref #95 アンインストール時に配信履歴データを削除する
  PluginManager.php
Labels: bugbounty2022:pr:entry

#140 参照していないjavascriptを削除
  Resource/template/admin/history_list.twig
  Resource/template/admin/index.twig
  Resource/template/admin/template_list.twig
Labels: bugbounty2022:pr:entry, bugbounty2022:pr:recognition

#142 参照していないjavascriptのコードを削除
  Resource/template/admin/index.twig
Labels: bugbounty2022:pr:entry, bugbounty2022:pr:recognition
